### ISSUE TITLE
Widget unable to initialize on Brave browser

### ISSUE THREAD

**Issue by PiotrNap** [nufi-official/nufi-dapp-sdk#10]
Hi! 

I have noticed a problem when I was trying to enable the widget on my site. I have a React.js website, and this is how my nufi-dapp-sdk related-code look like:

App.js
```
import { initNufiDappSdk } from "@nufi/dapp-client-core"
import { initNufiDappCardanoSdk } from "@nufi/dapp-client-cardano"

// warm up Nufi SSO widget
initNufiDappSdk()
initNufiDappCardanoSdk("sso")


// ... rest of the code ...
``` 

Home.js
```
  // ... main component ...
  const initiateSSOSignUp = async () => {
    let api

    try {
      const enabled = await window.cardano.nufiSSO.isEnabled()

      if (!enabled) {
        api = await window.cardano.nufiSSO.enable()
        if (!api) throw new Error("Unable to initialize NufiSSO")
      }
    } catch (e) {
      alert(e.message || e)
    }
  }
  
  // ... more code...
  
```

When I call the function on Brave browser, I get this in my console:

![Screenshot from 2024-01-27 16-45-20](https://github.com/nufi-official/nufi-dapp-sdk/assets/59693946/936237ef-8811-40ef-8160-58859e21c06b)
 
 
 Ps. Google Chrome and Firefox both work fine

**Comment by refi93** [comment]
Thanks for the report @PiotrNap , we are on it
